name: Generate and Publish Documentation

on:
  push:
    branches: ["main"]

jobs:
  generate-pages:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin
          ~/.cargo/registry/index
          ~/.cargo/registry/cache
          ~/.cargo/git/db
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Build
      run: cargo build --verbose

    - name: Test
      run: cargo test --verbose

    - name: Generate Documentation
      run: |
        cargo doc --no-deps
        echo "<meta http-equiv=\"refresh\" content=\"0; url=build_wheel\">" > target/doc/index.html

    - name: Upload Pages Artifact
      uses: actions/upload-pages-artifacts@v1
      with:
        path: './target/doc/'

  deploy-pages:
    needs: generate-pages

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Deploy To Pages
        id: deployment
        uses: actions/deploy-pages@v1